server:
  port: 9411
spring:
  sleuth:
    enabled: true
#  zipkin:
#    locator:
#      discovery:
#        enabled: true
  application:
    name: hms-zipkin #@@方式常用于引用springboot非默认配置文件（即其他配置文件）中的变量
#  cloud:
#    config:
#      profile: dev
#      name: service-user
#      label: master
#      uri: http://localhost:11113/
  rabbitmq:
    host: localhost
    port: 5672
    username: luoshao
    password: password
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    password: password
    pool:
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      #  最长等待时间
      max-wait: -1

  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间
zipkin:
  storage:
    type: mysql
eureka:
  instance:
    hostname: localhost # 服务提供者应用所在的主机（本地测试的话，使用localhost或者127.0.0.1即可，或者在host文件中指定一个虚拟域名也可以）
    lease-renewal-interval-in-seconds: 5 # 心跳时间，表示eureka client发送心跳给eureka server端的频率（缺省为30s）
  client:
    service-url:
      defaultZone: http://server.eureka.slav  e1.com:18761/eureka,http://server.eureka.slave2.com:28761/eureka # 指定eureka服务器集群列表地址